### ISSUE TITLE
Blog Site To-Do's

### ISSUE THREAD

**Issue by r3dact3d** [r3dact3d/r3dact3d.github.io#41]
- [x] Update Header Image
- [x] Update analytics email
- [x] Update About Section Images
- [x] Fix old image links
- [x] Review each post for small images
- [ ] Consider new title and description
- [x] Look for new features?
- [ ] Fix subscribe feed in footer.html
